quarkus.langchain4j.timeout=1m
process.vectors=false

quarkus.langchain4j.openai.api-key = demo
quarkus.langchain4j.openai.base-url = http://langchain4j.dev/demo/openai/v1
#quarkus.langchain4j.openai.api-key=

quarkus.langchain4j.openai.embedding-model.model-name=text-embedding-3-small