mp.messaging.incoming.email-in.auto.offset.reset=earliest
mp.messaging.incoming.email-in.topic=email
mp.messaging.outgoing.email-out.topic=email

mp.messaging.outgoing.spam-out.topic=spam
mp.messaging.outgoing.ham-out.topic=ham

mp.messaging.incoming.spam-in.topic=spam
mp.messaging.incoming.ham-in.topic=ham

quarkus.langchain4j.milvus.dimension=384
quarkus.langchain4j.openai.api-key = demo
quarkus.langchain4j.openai.base-url = http://langchain4j.dev/demo/openai/v1
